### ISSUE TITLE
Problem with using generate_train_data.py

### ISSUE THREAD

**Issue by AmberCheng** [GordonRen/pose2pose#5]
Hi, I want to use this program for study. I have used the anaconda, and build Openpose and Pyopenpose, but when I run the python script I get error as follow:

Traceback (most recent call last):
  File "generate_train_data.py", line 77, in <module>
    run()
  File "generate_train_data.py", line 17, in run
    False, OP.OpenPose.ScaleMode.ZeroToOne, with_face, with_hands)
Boost.Python.ArgumentError: Python argument types in
    OpenPose.__init__(OpenPose, tuple, tuple, tuple, str, str, int, bool, ScaleMode, bool, bool)
did not match C++ signature:
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool, bool, int)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>)
    __init__(_object*)
    __init__(_object*)

**Comment by GordonRen** [comment]
Please check the configuration environment of openpose.
